version: "3"
services:
    node7:
        build:
            context: .
            dockerfile: docker/Dockerfile-node7
        volumes:
            - ./:/home/node/app
        ports:
            - 8081:1337

    node6:
        build:
            context: .
            dockerfile: docker/Dockerfile-node6
        volumes:
            - ./:/home/node/app
        ports:
            - 8082:1337

    node-latest:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-latest
        volumes:
            - ./:/home/node/app
        ports:
            - 8083:1337

    node_8_alpine:
        build:
            context: .
            dockerfile: docker/test/Dockerfile-node-8-alpine
        volumes:
            - ./:/app/
        ports:
            - "3000:3003"

    node_7_alpine:
        build:
            context: .
            dockerfile: docker/test/Dockerfile-node-7-alpine
        volumes:
            - ./:/app/
        ports:
            - "3000:3001"

    node_6_alpine:
        build:
            context: .
            dockerfile: docker/test/Dockerfile-node-6-alpine
        volumes:
            - ./:/app/
        ports:
            - "3000:3002"
